apiVersion: v1
kind: Pod
metadata:
  name: netology-web
  labels:
    app: mission1
spec:
  containers:
  - name: hello-word-2
    image: gcr.io/kubernetes-e2e-test-images/echoserver:2.2
    #ports:
    #- containerPort: 80
