apiVersion: apps/v1
kind: Deployment
metadata:
  name: netology2
  labels:
    app: nginx
spec:
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
      - name: nginx
        image: nginx:1.14.2
      initContainers:
      - name: delay
        image: busybox
        command: ['sh', '-c', "until nslookup nginx-svc.default.svc.cluster.local; do echo waiting for nginx-svc; sleep 2; done; exit"]
