apiVersion: v1
kind: Pod
metadata:
  name: pod-multitool
  labels:
    app: multitool
spec:
      containers:
      - name: multitool
        image: wbitt/network-multitool
        env:
        - name: HTTP_PORT
          value: "1180"
        - name: HTTPS_PORT
          value: "11443"
        ports:
        - containerPort: 1180
          name: http-port
        - containerPort: 11443
          name: https-port
        securityContext:
          runAsUser: 0
          capabilities:
            add: ["NET_ADMIN"]