---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
spec:
  selector:
    matchLabels:
      app: multitool
      tier: backend
      track: stable
  replicas: 1
  template:
    metadata:
      labels:
        app: multitool
        tier: backend
        track: stable
    spec:
      containers:
      - name: network-multitool
        image: wbitt/network-multitool
        env:
        - name: HTTP_PORT
          value: "1180"          