---

#- name: Set hostname
  #ansible.builtin.hostname:
  #  name: "{{ inventory_hostname }}"
  #remote_user: vm1
  #become: yes
  #become_method: sudo

- name: Include vector installation
  ansible.builtin.import_tasks: vector.yml