---
- name: Install nginx
  ansible.builtin.apt:
    name: nginx
    state: latest
    update_cache: yes
    #when: ansible_os_family == "Debian"
  notify: Start Nginx
    
- name: Template a file to /etc/nginx/conf.conf
  ansible.builtin.template:
    src: ./roles/lighthouse/tamplates/nginx.conf.j2
    dest: /etc/nginx/nginx.conf