--- 
all:
  hosts:
    jenkins-agent-01:
      ansible_host: 158.160.96.237
    jenkins-master-01:
      ansible_host: 158.160.120.180
  children:
    jenkins:
      children:
        jenkins_masters:
          hosts:
            jenkins-master-01:
        jenkins_agents:
          hosts:
              jenkins-agent-01:

  vars:
    ansible_connection_type: paramiko
    ansible_user: aos            

