apiVersion: apps/v1
kind: Deployment
metadata:
  name: deploy
  labels:
    app: mission1
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mission1
  template:
    metadata:
      labels:
        app: mission1
    spec:
      containers:
      - name: delay
        image: busybox
        command: ['sh', '-c', "while true; do echo $(date) > /output/success.txt; sleep 5; done"]
        volumeMounts: 
        - mountPath: /output
          name: vol
      - name: network-multitool
        image: wbitt/network-multitool
        env:
        - name: HTTP_PORT
          value: "1180"
        volumeMounts: 
        - mountPath: /output
          name: vol       
      volumes:
      - name: vol
        emptyDir: {}      
