--- 
all:
  hosts:
    nexus-01:
      ansible_host: 89.169.136.186
  children:
    nexus:
      hosts:
        nexus-01:

  vars:
    ansible_connection_type: paramiko
    ansible_user: aos           


