apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.nginx.name }}-frontend
spec:
  selector:
    app: {{ .Values.nginx.name }}
  ports:
    - name: {{ .Values.nginx.name }}
      protocol: TCP
      port: 80
      targetPort: 80