apiVersion: v1
kind: Service
metadata:
  name: svc-mission2
spec:
  selector:
    app: nginx-multitool
  type: NodePort
  ports:
    - name: nginx
      protocol: TCP
      port: 80
      nodePort: 30000