apiVersion: v1
kind: Service
metadata:
  name: netology-svc
spec:
  selector:
    app: mission1
    #app.kubernetes.io/name: mission1
  ports:
    - name: netology
      protocol: TCP
      port: 30000
      targetPort: 8080
