---
  - name: update systemd
    package: name="systemd" state="latest"
    when: "ansible_connection == 'docker'"
  - name: install systemctl.py
    copy: src="./files/docker/systemctl.py" dest="/usr/bin/systemctl"
    when: "ansible_connection == 'docker'"


  #- name: install python for systemctl.py
  #  package: name=python
  #  when: "ansible_connection == 'docker'"
  - name: ensure run directory for ansible check_systemd
    file: name="/run/systemd/system/" state="directory"
    when: "ansible_connection == 'docker'"
  - name: check some service
    service: name="dbus.service" state="stopped"