apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: daemonset
  #namespace: kube-system
  labels:
    k8s-app: mission2
spec:
  selector:
    matchLabels:
      name: mission2
  template:
    metadata:
      labels:
        name: mission2
    spec:
      containers:
      - name: network-multitool
        image: wbitt/network-multitool
        resources:
          limits:
        env:
        - name: HTTP_PORT
          value: "1180"
        volumeMounts:
        - name: varlog
          mountPath: /var/log/syslog
      # it may be desirable to set a high priority class to ensure that a DaemonSet Pod
      # preempts running Pods
      # priorityClassName: important
      terminationGracePeriodSeconds: 30
      volumes:
      - name: varlog
        hostPath:
          path: /var/log/syslog