---
  - name: Print os facts
    hosts: all
    #remote_user: vm1
    #become: yes 
    #become_user: root
    #become_method: sudo
 
    tasks:
      - name: Print OS
        debug:
          msg: "{{ ansible_distribution }}"
      - name: Print fact
        debug:
          msg: "{{ some_fact }}"

  - name: Clickhouse installation & configuration
    hosts: clickhouse
    gather_facts: true
    roles:
      - { role: clickhouse }
      
  - name: Vector installation & configuration
    hosts: vector
    gather_facts: true
    roles:
      - { role: vector }


