apiVersion: v1
kind: Service
metadata:
  name: svc-mission1
spec:
  selector:
    app: nginx-multitool
  ports:
    - name: nginx
      protocol: TCP
      port: 9001
      targetPort: 80
    - name: mooltitool
      protocol: TCP
      port: 9002
      targetPort: 8080