apiVersion: v1
kind: Service
metadata:
  name: svc-nginx
  namespace: mission1
spec:
  selector:
    app: nginx-mt
  type: NodePort
  ports:
    - name: nginx
      protocol: TCP
      port: 80
      targetPort: 80
      nodePort: 30080